apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
spec:
  replicas: 1
  selector:
    matchlabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: guillaumemaiano/event-bus-app-udemy-grider
### triple dash allows writing another config file in the same file (e.g., "colocation of definitions").
---
apiVersion: apps/v1
kind: Service
metadata:
  name: event-bus-srv
spec:
# type defaults to ClusterIP, so the following line is optional
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005