# Supersedes the former pod-description left in the example subfolder
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  replicas: 1
  selector:
    matchlabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          #image: guillaumemaiano/posts-app-udemy-grider:0.0.1
          # not specifying a version number defaults to latest, as in docker
          image: guillaumemaiano/posts-app-udemy-grider
