# Individual pod
# Superseded in the project by a deployment yaml caled posts-depl.yaml
apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
  - name: posts
    image: guillaumemaiano/posts-app-udemy-grider:0.0.1